package me.lenaic.httpcommands;

import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.util.UUID;
import java.util.logging.Level;

/**
 * Manages plugin configuration for port and bearer token
 * Auto-generates a secure bearer token on first run
 */
public class ConfigManager {

    private final JavaPlugin plugin;
    private FileConfiguration config;
    private File configFile;

    private int port;
    private String bearerToken;
    private boolean requireHttps;
    private boolean tokenAutoGenerated;

    public ConfigManager(JavaPlugin plugin) {
        this.plugin = plugin;
    }

    /**
     * Load configuration from config.yml
     */
    public void loadConfig() {
        // Ensure plugin data folder exists
        File dataFolder = plugin.getDataFolder();
        if (!dataFolder.exists()) {
            dataFolder.mkdirs();
        }

        // Create config file if it doesn't exist
        if (configFile == null) {
            configFile = new File(dataFolder, "config.yml");
        }

        if (!configFile.exists()) {
            // Copy default config from resources
            try (InputStream in = plugin.getResource("config.yml")) {
                if (in != null) {
                    Files.copy(in, configFile.toPath());
                }
            } catch (IOException e) {
                plugin.getLogger().log(Level.SEVERE, "Could not create config file", e);
            }
        }

        config = YamlConfiguration.loadConfiguration(configFile);

        // Load values
        port = config.getInt("port", 8080);
        requireHttps = config.getBoolean("require-https", false);
        
        // Handle bearer token - auto-generate if not set
        bearerToken = config.getString("bearer-token", null);
        if (bearerToken == null || bearerToken.isEmpty() || bearerToken.equals("change-me-to-a-secure-token")) {
            // Generate new secure token
            bearerToken = generateSecureToken();
            tokenAutoGenerated = true;
            config.set("bearer-token", bearerToken);
            
            // Save the config with the new token
            try {
                config.save(configFile);
                plugin.getLogger().info("✓ Auto-generated secure bearer token and saved to config.yml");
            } catch (IOException e) {
                plugin.getLogger().log(Level.SEVERE, "Could not save config file with generated token", e);
            }
        }

        plugin.getLogger().info("✓ ProMcScure Configuration loaded - Port: " + port + ", Require HTTPS: " + requireHttps);
    }

    /**
     * Generate a secure random bearer token
     */
    private String generateSecureToken() {
        // Generate a token using UUID (or could use UUID + random string for extra security)
        return "token_" + UUID.randomUUID().toString().replace("-", "");
    }

    /**
     * Reload configuration from file
     */
    public void reloadConfig() {
        loadConfig();
    }

    public int getPort() {
        return port;
    }

    public String getBearerToken() {
        return bearerToken;
    }

    public boolean isRequireHttps() {
        return requireHttps;
    }

    public boolean isTokenAutoGenerated() {
        return tokenAutoGenerated;
    }

    public FileConfiguration getConfig() {
        return config;
    }
}
