package me.lenaic.httpcommands;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;
import org.bstats.bukkit.Metrics;

import java.util.List;

/**
 * Main plugin class for ProMcScure plugin
 * Provides HTTP/REST API endpoint to execute Minecraft console commands
 */
public final class HttpCommandsPlugin extends JavaPlugin implements Listener {

    private ConfigManager configManager;
    private HttpServerManager httpServerManager;
    private PendingCommandManager pendingCommandManager;
    private boolean setupDisplayed = false;

    @Override
    public void onEnable() {
        // Initialize configuration manager
        configManager = new ConfigManager(this);
        configManager.loadConfig();

        // Initialize pending command manager (loads from file)
        pendingCommandManager = new PendingCommandManager(this);

        // Initialize and start HTTP server
        httpServerManager = new HttpServerManager(this, configManager, pendingCommandManager);
        httpServerManager.start();

        int pluginId = 29591;
        new Metrics(this, pluginId);

        // Register event listener for player join
        getServer().getPluginManager().registerEvents(this, this);

        // Display setup information
        displaySetupInfo();

        getLogger().info("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        getLogger().info("ProMcScure plugin enabled!");
        getLogger().info("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    }

    @Override
    public void onDisable() {
        // Stop HTTP server
        if (httpServerManager != null) {
            httpServerManager.stop();
        }

        getLogger().info("ProMcScure plugin disabled!");
    }

    /**
     * Display setup information on first enable
     */
    private void displaySetupInfo() {
        if (setupDisplayed) {
            return;
        }
        setupDisplayed = true;

        String port = String.valueOf(configManager.getPort());
        String token = configManager.getBearerToken();
        boolean autoGenerated = configManager.isTokenAutoGenerated();

        getLogger().info("");
        getLogger().info("╔════════════════════════════════════════╗");
        getLogger().info("║         ProMcScure Setup Guide         ║");
        getLogger().info("╚════════════════════════════════════════╝");
        getLogger().info("");
        
        if (autoGenerated) {
            getLogger().info("✓ AUTO-GENERATED BEARER TOKEN:");
            getLogger().info("  " + token);
            getLogger().info("");
        }
        
        getLogger().info("📱 REST API Configuration:");
        getLogger().info("  Base URL: http://YOUR_SERVER_IP:" + port);
        getLogger().info("  Authorization: Bearer " + token);
        getLogger().info("");
        
        getLogger().info("📚 Available Endpoints:");
        getLogger().info("  GET  /info          - Server information");
        getLogger().info("  GET  /players       - Online players list");
        getLogger().info("  GET  /player/{name} - Player details");
        getLogger().info("  POST /execute       - Execute commands");
        getLogger().info("");
        
        getLogger().info("🔗 Setup with REST Client:");
        getLogger().info("  1. Install REST client (Postman, Thunder Client, etc)");
        getLogger().info("  2. Create new request");
        getLogger().info("  3. Set Authorization → ******");
        getLogger().info("  4. Paste token above");
        getLogger().info("  5. Test with: GET http://YOUR_SERVER_IP:" + port + "/info");
        getLogger().info("");
        
        getLogger().info("📖 Full documentation available in SETUP_GUIDE.md");
        getLogger().info("📱 Mobile guide available in MOBILE_REQUESTS.md");
        getLogger().info("");
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (command.getName().equalsIgnoreCase("promcscure") || command.getName().equalsIgnoreCase("http-commands")) {
            if (args.length == 0) {
                showHelp(sender);
                return true;
            }

            if (args[0].equalsIgnoreCase("reload")) {
                if (!sender.hasPermission("promcscure.admin") && !sender.hasPermission("httpcommands.reload")) {
                    sender.sendMessage("§c✗ You don't have permission to use this command.");
                    return true;
                }

                // Reload configuration
                configManager.reloadConfig();

                // Restart HTTP server with new config
                httpServerManager.stop();
                httpServerManager = new HttpServerManager(this, configManager, pendingCommandManager);
                httpServerManager.start();

                sender.sendMessage("§a✓ Configuration reloaded and HTTP server restarted!");
                return true;
            }

            if (args[0].equalsIgnoreCase("token")) {
                if (!sender.hasPermission("promcscure.admin")) {
                    sender.sendMessage("§c✗ You don't have permission to use this command.");
                    return true;
                }

                sender.sendMessage("§6━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
                sender.sendMessage("§6ProMcScure ******");
                sender.sendMessage("§a" + configManager.getBearerToken());
                sender.sendMessage("§6━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
                return true;
            }

            if (args[0].equalsIgnoreCase("status")) {
                if (!sender.hasPermission("promcscure.admin")) {
                    sender.sendMessage("§c✗ You don't have permission to use this command.");
                    return true;
                }

                sender.sendMessage("§6━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
                sender.sendMessage("§aProMcScure Status:");
                sender.sendMessage("§6  Port: §a" + configManager.getPort());
                sender.sendMessage("§6  HTTPS Required: §a" + (configManager.isRequireHttps() ? "Yes" : "No"));
                sender.sendMessage("§6  Server Running: §aYes");
                sender.sendMessage("§6━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
                return true;
            }

            showHelp(sender);
            return true;
        }

        return false;
    }

    private void showHelp(CommandSender sender) {
        sender.sendMessage("§6━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        sender.sendMessage("§6ProMcScure Commands:");
        sender.sendMessage("§a/promcscure reload  §6- Reload configuration");
        sender.sendMessage("§a/promcscure token   §6- Show bearer token");
        sender.sendMessage("§a/promcscure status  §6- Show server status");
        sender.sendMessage("§6━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    }

    public ConfigManager getConfigManager() {
        return configManager;
    }

    public PendingCommandManager getPendingCommandManager() {
        return pendingCommandManager;
    }

    /**
     * Handle player join event - execute pending commands for the player
     */
    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent event) {
        String playerName = event.getPlayer().getName();
        
        if (pendingCommandManager.hasPendingCommands(playerName)) {
            getLogger().info("Player " + playerName + " joined, executing pending commands");
            
            // Execute pending commands asynchronously
            Bukkit.getScheduler().runTaskAsynchronously(this, () -> {
                List<List<String>> pendingCommands = pendingCommandManager.getAndRemovePendingCommands(playerName);
                
                if (pendingCommands != null) {
                    for (List<String> commands : pendingCommands) {
                        executeCommands(commands);
                    }
                }
            });
        }
    }

    /**
     * Execute a list of commands synchronously on the main server thread
     */
    private void executeCommands(List<String> commands) {
        Bukkit.getScheduler().runTask(this, () -> {
            for (String command : commands) {
                boolean success = Bukkit.dispatchCommand(Bukkit.getConsoleSender(), command);
                if (success) {
                    getLogger().info("Executed pending command: " + command);
                } else {
                    getLogger().warning("Failed to execute pending command: " + command);
                }
            }
        });
    }
}
